apiVersion: v2
name: one-data-studio
description: ONE-DATA-STUDIO - Enterprise DataOps + MLOps + LLMOps Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - dataops
  - mlops
  - llmops
  - ai
  - data-platform
home: https://github.com/one-data-studio
maintainers:
  - name: ONE-DATA-STUDIO Team
    email: team@one-data-studio.io
dependencies:
  - name: mysql
    version: "9.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  - name: redis
    version: "17.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: minio
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
