# OpenAI Proxy Deployment
# OpenAI-compatible API proxy for model serving
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openai-proxy
  namespace: one-data-studio
  labels:
    app.kubernetes.io/name: openai-proxy
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: one-data-studio
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: openai-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openai-proxy
        app.kubernetes.io/component: proxy
    spec:
      serviceAccountName: one-data-api
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: openai-proxy
          image: one-data-studio/openai-proxy:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            # ConfigMap values
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: one-data-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: one-data-config
                  key: REDIS_PORT
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: one-data-config
                  key: ENVIRONMENT
            - name: AUTH_MODE
              valueFrom:
                configMapKeyRef:
                  name: one-data-config
                  key: AUTH_MODE
            - name: KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  name: one-data-config
                  key: KEYCLOAK_URL
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: one-data-config
                  key: KEYCLOAK_REALM
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: one-data-config
                  key: KEYCLOAK_CLIENT_ID
            # Secret values
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: one-data-secrets
                  key: REDIS_PASSWORD
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: one-data-secrets
                  key: JWT_SECRET_KEY
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: one-data-secrets
                  key: KEYCLOAK_CLIENT_SECRET
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: one-data-secrets
                  key: OPENAI_API_KEY
                  optional: true
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: openai-proxy
                topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: openai-proxy
  namespace: one-data-studio
  labels:
    app.kubernetes.io/name: openai-proxy
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8003
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: openai-proxy
