# Pod Disruption Budget
# Ensures minimum availability during voluntary disruptions

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: agent-api-pdb
  namespace: one-data-studio
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: agent-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: data-api-pdb
  namespace: one-data-studio
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: data-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: openai-proxy-pdb
  namespace: one-data-studio
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: openai-proxy
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: model-api-pdb
  namespace: one-data-studio
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: model-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web-frontend-pdb
  namespace: one-data-studio
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web-frontend
